# Generated by Django 5.0.6 on 2024-06-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_food_vegitarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='vegitarian',
        ),
        migrations.AddField(
            model_name='food',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
