# Generated by Django 5.0.6 on 2024-06-07 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_food_vegitarian_food_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
