# Generated by Django 5.0.6 on 2024-06-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_food_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='review',
        ),
    ]
